version: '3.9'

services:
  licensingservice:

    image: licensing-service:latest

    ports:
      - "8080:8080"

    environment:
      - "SPRING_PROFILES_ACTIVE=dev"

    networks:
      backend:
        aliases:
            - "licenseservice"
  postgres:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "ostock_dev"
networks:
  backend:
    driver: "bridge"