spring:
  application:
    name: licensing-service
  profiles:
    active: dev
  config:
    import: configserver:http://configserver:8071

management:
  endpoints:
    web:
      base-path: /
    enabled-by-default: 'false'
  health:
    diskspace:
      enabled: 'true'
    db:
      enabled: 'false'
  endpoint:
    health:
      enabled: 'true'
      show-details: always