eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    serviceUrl:
      defaultZone:
        http://eurekaserver:8070/eureka/
spring:
  application:
    name: organization-service
    profiles: dev
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    database: POSTGRESQL
    hibernate:
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
      ddl-auto: none
    show-sql: 'true'
  datasource:
    testWhileIdle: 'true'
    validationQuery: SELECT 1
    platform: postgres
    url: jdbc:postgresql://localhost:5432/ostock
    username: postgres
    password: postgres
  database:
    driverClassName: org.postgresql.Driver
  cloud:
    loadbalancer:
      ribbon:
        enabled: false
server:
  port: 8081

management:
  endpoints:
    web:
      exposure:
        include: '*'
    enabled-by-default: 'true'
